// 原版 Minecraft 方块贴图逐像素转录(脚本自动生成,勿手改)
// 来源: InventivetalentDev minecraft-assets 镜像(1.20.4 block/*.png)
// grassTop/leaves 原文件为灰度,渲染时按原版规则乘群系色

export interface McBlockSprite {
    palette: Record<string, string>;
    rows: string[];
}

export const MC_BLOCK_SPRITES: Record<string, McBlockSprite> = {
    grassTop: { palette: { 'A': '#949494', 'B': '#c3c3c3', 'C': '#939393', 'D': '#868686', 'E': '#8f8f8f', 'F': '#7f7f7f', 'G': '#8c8c8c', 'H': '#9e9e9e', 'I': '#969696', 'J': '#8a8a8a', 'K': '#878787', 'L': '#898989', 'M': '#a7a7a7', 'N': '#707070', 'O': '#8d8d8d', 'P': '#959595', 'Q': '#a0a0a0', 'R': '#979797', 'S': '#999999', 'T': '#808080', 'U': '#828282', 'V': '#a9a9a9', 'W': '#a6a6a6', 'X': '#8b8b8b', 'Y': '#a3a3a3', 'Z': '#7d7d7d', 'a': '#848484', 'b': '#888888', 'c': '#909090', 'd': '#9f9f9f', 'e': '#a8a8a8', 'f': '#adadad', 'g': '#777777', 'h': '#b6b6b6', 'i': '#767676', 'j': '#858585', 'k': '#919191', 'l': '#929292', 'm': '#838383', 'n': '#a2a2a2', 'o': '#acacac', 'p': '#aeaeae', 'q': '#bababa', 'r': '#757575', 's': '#ababab', 't': '#7e7e7e', 'u': '#989898', 'v': '#787878', 'w': '#818181', 'x': '#9b9b9b', 'y': '#8e8e8e', 'z': '#9c9c9c', '0': '#a5a5a5', '1': '#b5b5b5', '2': '#9d9d9d', '3': '#7c7c7c', '4': '#a4a4a4', '5': '#aaaaaa', '6': '#b3b3b3', '7': '#b7b7b7', '8': '#c0c0c0', '9': '#797979', '!': '#7b7b7b', '@': '#7a7a7a', '#': '#a1a1a1', '$': '#bfbfbf' }, rows: [
        'ABCDDEFGHIJKLMNO',
        'PGQRSTSUFVWCBGKX',
        'YOZaLbccAdefKgTh',
        'ijJRkSZlFmOREXMZ',
        'nmfmopboqrTMstbO',
        'SuvWwIPxKPbmvbyA',
        'tz0clmJFaK1okMRE',
        'EK2Xc34aRfKwEQFV',
        'Mxh5owfz65UljCHt',
        'RU7OGu5TKklVy6Ew',
        'xHR0UhyC89MmEbRE',
        'afDYRalLRlG!6FZJ',
        'qRwJSkj@JkJZd09R',
        'weilZSwB#CexQbep',
        'Y#8!6sACtPPKV2X9',
        'jIbL4uACy$3VacbH',
    ] },
    grassSide: { palette: { 'A': '#74b44a', 'B': '#76b64c', 'C': '#73b349', 'D': '#66a63c', 'E': '#6faf45', 'F': '#5f9f35', 'G': '#6cac42', 'H': '#7ebe54', 'I': '#6aaa40', 'J': '#67a73d', 'K': '#69a93f', 'L': '#61a137', 'M': '#509026', 'N': '#6dad43', 'O': '#75b54b', 'P': '#8ab95a', 'Q': '#81b051', 'R': '#83b253', 'S': '#593d29', 'T': '#68a83e', 'U': '#62a238', 'V': '#93c263', 'W': '#90bf60', 'X': '#6bab41', 'Y': '#8dbc5d', 'Z': '#9ccb6c', 'a': '#64a43a', 'b': '#70b046', 'c': '#7fbf55', 'd': '#92c162', 'e': '#97c667', 'f': '#57972d', 'g': '#60a036', 'h': '#6c6c6c', 'i': '#71b147', 'j': '#79553a', 'k': '#966c4a', 'l': '#b9855c', 'm': '#878787', 'n': '#745844' }, rows: [
        'ABCDDEFGHBIJKLMN',
        'OGPQRSTUFVWCLGJX',
        'YSZaKSbSAcdeSfgS',
        'ShSSiSSSFSNSjSSj',
        'kjklSkjjSSShjkSj',
        'jSkkjkSSSjjSjjjl',
        'ljjjmjjlljlljkjk',
        'jjllkkjjkSkkjjkk',
        'kjjkjkjSjkkjjjSj',
        'jkSjjSSjjjjjlljk',
        'jkjlljlkSllSkkmj',
        'kjjkkljkhkkjSkjS',
        'jSkjkkljjjjjjjll',
        'jkjjnjkkjSlSjlkk',
        'kjSljSjSlljkjjkk',
        'kjlkkjmjkkjjkkjS',
    ] },
    dirt: { palette: { 'A': '#b9855c', 'B': '#966c4a', 'C': '#79553a', 'D': '#593d29', 'E': '#878787', 'F': '#6c6c6c', 'G': '#745844' }, rows: [
        'ABBCCABBCCDCCACA',
        'CBDCCBEDCABCABDD',
        'ACCDACCCACCCDDAC',
        'BFACBDCABBCBCABC',
        'BCBADBCCBDCFCBDC',
        'CDBBCBDDDCCDCCCA',
        'ACCCECCAACAACBCB',
        'CCAABBCCBDBBCCBB',
        'BCCBCBCDCBBCCCDC',
        'CBDCCDDCCCCCAACB',
        'CBCAACABDAADBBEC',
        'BCCBBACBFBBCDBCD',
        'CDBCBBACCCCCCCAA',
        'CBCCGCBBCDADCABB',
        'BCDACDCDAACBCCBB',
        'BCABBCECBBCCBBCD',
    ] },
    stone: { palette: { 'A': '#8f8f8f', 'B': '#7f7f7f', 'C': '#747474', 'D': '#686868' }, rows: [
        'AAAABCCBCDCCBBBB',
        'BBCBCBBBBBBDDCBC',
        'BCDDCCCDCCCBBBBB',
        'BBAABABBAABBBCCC',
        'CBBCCCBCBAAAACBB',
        'BABBBBBBBCCDCDCA',
        'CBBAAACAACCCBBBB',
        'CCDDCDCCBBCCCBBB',
        'AAABABBAAABBBBBC',
        'BBABBBAAABBAAAAB',
        'DBCBCCDDCBCBBCCC',
        'BBBBBAABBBBBAABA',
        'BCCCBABCCBBDDCDC',
        'AABCCBBCCCBBCCCA',
        'BCCBBBBBBBBBAAAA',
        'BBBBBBCCBAABBCBB',
    ] },
    cobble: { palette: { 'A': '#6e6d6d', 'B': '#616161', 'C': '#a6a6a6', 'D': '#525252', 'E': '#b5b5b5', 'F': '#888788' }, rows: [
        'ABCCDBBCECFBFECF',
        'BCEFFDEECFFDBFAF',
        'BCFCABCFFCABDBFA',
        'BBFABBFAFABFCFBD',
        'DABFECBFBBECCCFB',
        'EACEFFABDFFECFAF',
        'CFBFCFFABBACFABE',
        'FFAAFFABFECBAFBF',
        'ABECAABFEFFFBBDA',
        'BECFAFAAFFBABFCB',
        'FAFAFBBDBAABDCCE',
        'FAABBAFECBBDFEEF',
        'AFECABECFCABFFAF',
        'BECFFBCFAFFABBFA',
        'CCFAFABAFFABCFBB',
        'BFBBAFABABBFECFA',
    ] },
    logSide: { palette: { 'A': '#745a36', 'B': '#4c3d26', 'C': '#917142', 'D': '#382b18', 'E': '#5f4a2b', 'F': '#987849' }, rows: [
        'ABCAADCAADACBCAE',
        'ABFEADFEADACBAAE',
        'ADEEADFEABABBAAE',
        'CDAEABAEAEADBACE',
        'CBAEADAEFEAEABCA',
        'CABACBABFECBABCA',
        'EABACEEACACAABCA',
        'EADACAECAACEAECA',
        'ABDFAAECAECECECA',
        'AABFAAEAAECBCADA',
        'AAACAEADAEABCADA',
        'ABACAEADFAADFABA',
        'FBAACECDFEADAAEA',
        'FABACAABCEABAAAA',
        'CABCAACDABABBCAA',
        'CABCBACBABAABCAE',
    ] },
    logTop: { palette: { 'A': '#5f4a2b', 'B': '#4c3d26', 'C': '#745a36', 'D': '#b8945f', 'E': '#af8f55', 'F': '#c29d62', 'G': '#7e6237', 'H': '#967441', 'I': '#9f844d' }, rows: [
        'ABACABAACBAABAAA',
        'BDDDDEDEFEEDDDDB',
        'ADGGHHIHIIIIHHFA',
        'ADGFFDDDDEDDDHDA',
        'AEHDEEEEEEEEDIEA',
        'BDIDEHHIIHHEDHEB',
        'AEHEEGEEEEHEEHDA',
        'AEIDEHEIIEIEDIEA',
        'AEIDEHEIHEHEDHEA',
        'BEIDEHEEEEIEEHEB',
        'AEHDEHHGHIIEDIEA',
        'AEIDEEEEEEEEDHEA',
        'BDIDDEDDDDDFDHEB',
        'ADIHIHHHHHHHHHDA',
        'ADDDEEDEEFEEDDDA',
        'ABAAABAACBAABCAA',
    ] },
    leaves: { palette: { 'A': '#686468', 'B': '#b9bcb9', 'C': '#989998', 'D': '#777577' }, rows: [
        'AA.B.CC.DDAC..BD',
        'C...AADC.CDC.BCB',
        '..DD.CCDB.C..BBB',
        '.CDAA.BCBA....B.',
        'CDCD..CB...ACC..',
        'CCD..BDAAA..ADC.',
        'DD.ABCBC.DD.CCDB',
        'DAA.BBB.AADC.BDC',
        'BC.AABCC.DCDC.CD',
        'B...AAADC.CCC.BC',
        '.CC.A.CCDB.C...B',
        'BDAA...BCB.DC...',
        'DCC.CC..B.AADB.B',
        'CB.BDAA..A.CBDCB',
        'B.BCBC..DD..BCB.',
        'C.BBB..AAAD..B.C',
    ] },
    sand: { palette: { 'A': '#e7e4bb', 'B': '#dacfa3', 'C': '#e3dbb0', 'D': '#d5c496', 'E': '#d1ba8a', 'F': '#edebcb' }, rows: [
        'ABBCBDCBCBDCBCDC',
        'DBBDBDDCEDABFEBA',
        'CBEDDABBBBBDBDDB',
        'BCCDBDCDCCDCBDBB',
        'DBFBDCBCBCBBDBBC',
        'BDBBCCCBDBCDBBDB',
        'DABDDFDBDDEBBDBD',
        'BDBBDBBDBDDDBABD',
        'DBCBBCDEDCDBCBDB',
        'ABDBBBDDBEBDBBCD',
        'BEBCBDBCBBCBEDBC',
        'DDBBCBDBCCDDDBDB',
        'DBDCDCBDAFCBDDBC',
        'CBCBCEBCBCBCBBDB',
        'BCBCFCCBCBCBECBB',
        'CBCBCCBCBDBBCBCB',
    ] },
    birchSide: { palette: { 'A': '#f0eeeb', 'B': '#ded3d5', 'C': '#d8d8ce', 'D': '#ffffff', 'E': '#bebeae', 'F': '#605e54', 'G': '#36342a', 'H': '#eef1ea' }, rows: [
        'AABCCAAACBAACCAA',
        'CBAAAADDDACBBBCA',
        'DDDBBCADAAAACADD',
        'DDCEFGGFCADDDDCD',
        'CAACEFFGFCDDACFE',
        'FFCCACBBCACCCFGG',
        'FEAACBBADDDAAHCE',
        'CBCDDDDDDCCBHHAC',
        'DACCADDHHDDDDHDD',
        'DDABBHHHDDDAACCA',
        'CCADDDDAAACBBDDA',
        'CADDDDADDDDHDDAC',
        'BBCAACCAADHHCEFG',
        'GEAADDDACBBCFGGG',
        'GGFCCCDDDAFFCEFF',
        'ACCFADDDABCCACCA',
    ] },
    hay: { palette: { 'A': '#8a7320', 'B': '#bfab31', 'C': '#94801e', 'D': '#cbb630', 'E': '#ab9225', 'F': '#a5492c', 'G': '#a4512b', 'H': '#924123', 'I': '#87351c' }, rows: [
        'ABCBADCBCBEBCBED',
        'CBCBCDCBCECBEBAE',
        'ACEBABCEACAEAEEE',
        'FGHGGGHHHIHGGGHG',
        'CECEAECECECEAEAC',
        'CBEBCBADAECECEAE',
        'EBEDCBCDEBEDCECB',
        'EBEDEDCBEDEBEDED',
        'EDEDEDEDEDEDEDED',
        'EDCDEDEDEBEDEDCB',
        'ADCBCECEECCBABEB',
        'HHGGFHFGFHHGGGHG',
        'ACCAAAACACCEACAC',
        'AEAACEAEAECCACAE',
        'CEAECBABCBCEAEAD',
        'AECBADCBADEDCDCD',
    ] },
    planks: { palette: { 'A': '#b8945f', 'B': '#af8f55', 'C': '#c29d62', 'D': '#967441', 'E': '#9f844d', 'F': '#7e6237', 'G': '#67502c' }, rows: [
        'ABACCCCCACCCCCAD',
        'AABBDEBAAABBAAEE',
        'BAAABABEEEEBBAAD',
        'DFFDDFGGFFGFGGFG',
        'ACECCCCECCCABBEA',
        'BAABEBEDEBBAAAAB',
        'EEBABBBDAAABBEEE',
        'GGFFDFGGGGFFFDFG',
        'ACCABBCCCCCCCCAE',
        'ABAAAABEEEBEBEED',
        'CABBEEEEBBBBEEAE',
        'GGFDDFGGGFDFFGGG',
        'CEACCAAECCCECACC',
        'BBAAEEBEEAABABBB',
        'BEEBABEDAABEEEEE',
        'GFFGGFDDDFGFGGGG',
    ] }
};

export const MC_STEVE_FACE: string[] = [
    'hhhhhhhh',
    'hhhhhhhh',
    'hssssssh',
    'ssssssss',
    'swissiws',
    'ssssssss',
    'ssssssss',
    'ssssssss',
];
