import { chromium } from '@playwright/test';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1280, height: 900 } });
const errors = [];
page.on('console', m => { if (m.text().includes('OFFLINE-DEBUG')) console.log('DBG:', m.text()); });
page.on('pageerror', e => errors.push(String(e).slice(0, 300)));
page.on('console', m => { if (m.type() === 'error') errors.push('CONSOLE: ' + m.text().slice(0, 200)); });
await page.goto('http://localhost:3907', { waitUntil: 'domcontentloaded' });
await page.evaluate(() => localStorage.clear());
await page.reload({ waitUntil: 'domcontentloaded' });
await page.getByText('经典标准局', { exact: false }).first().click();
await page.getByTestId('ignite-campfire-button').click();
await page.waitForTimeout(15000);
const logs = await page.evaluate(() => JSON.parse(localStorage.getItem('werewolf-currentLogs') || '[]').map(l => l.content.split('\n')[0].slice(0, 40)));
console.log('日志条数:', logs.length);
console.log('离线提示条目:', logs.filter(l => l.includes('离线') || l.includes('未检测')).join(' | ') || '无');
console.log(logs.slice(0, 6).join('\n'));
console.log('ERRORS:', errors.join(' ;; ') || 'none');
await browser.close();
