// 原版 Minecraft 贴图逐像素转录(脚本自动生成,勿手改)
// 来源: Mojang bedrock-samples(campfire/steve/alex/bread/heart/bone/emerald/torch/map)
//       与 InventivetalentDev minecraft-assets 镜像(sword/bow/potion/shovel/redstone/door/book/compass)
// shield 无官方平面贴图,按原版木纹+铁色板手绘

export interface McSprite {
    w: number;
    h: number;
    palette: Record<string, string>;
    rows: string[];
}

export const MC_SPRITES: Record<string, McSprite> = {
    campfire: { w: 16, h: 16, palette: { A: '#b13f00', B: '#c96c03', C: '#dfa21b', D: '#efcd56', E: '#f9ebab', F: '#4c3d26', G: '#fefefb', H: '#c29d62', I: '#b8945f', J: '#362b1b', K: '#9f844d', L: '#5f4a2b', M: '#967441', N: '#745a36', O: '#917142', P: '#987849' }, rows: [
    '................',
    '........A.......',
    '.......AAA......',
    '.......BBA......',
    '.....A.CBBA.....',
    '.....ABCCBA.....',
    '....ABCDDCBA....',
    '....BCDDEDCB....',
    '...FABCEGDBAF...',
    '..FHIHBGGBHIHJ..',
    '.FFHKIAGEAHKIJJ.',
    '.FLIIMLNNOIIMLJ.',
    '.FNLFFNOONLFFNJ.',
    '.FPPNNONLLLNNOJ.',
    '.JJJJJJJJJJJJJJ.',
    '................',
    ] },
    steve: { w: 16, h: 32, palette: { A: '#2f200d', B: '#2b1e0d', C: '#2f1f0f', D: '#281c0b', E: '#241808', F: '#261a0a', G: '#2a1d0d', H: '#332411', I: '#422a12', J: '#3f2a15', K: '#2c1e0e', L: '#b6896c', M: '#bd8e72', N: '#c69680', O: '#bd8b72', P: '#bd8e74', Q: '#ac765a', R: '#342512', S: '#aa7d66', T: '#b4846d', U: '#ad806d', V: '#9c725c', W: '#bb8972', X: '#9c694c', Y: '#ffffff', Z: '#523d89', a: '#b57b67', b: '#9c6346', c: '#b37b62', d: '#b78272', e: '#6a4030', f: '#be886c', g: '#a26a47', h: '#805334', i: '#905e43', j: '#965f40', k: '#774235', l: '#8f5e3e', m: '#815339', n: '#6f452c', o: '#6d432a', p: '#7a4e33', q: '#83553b', r: '#009e9e', s: '#00a8a8', t: '#00afaf', u: '#009999', v: '#966f5b', w: '#463aa5', x: '#3a3189', y: '#6b6b6b' }, rows: [
    '....ABCDEFBG....',
    '....BBBHIJKD....',
    '....BLMNOPQR....',
    '....STSUVWXX....',
    '....TYZaWZYS....',
    '....bcdeefgh....',
    '....ijkkkklm....',
    '....nommpqqp....',
    'rstsurmgmmrrstsr',
    'tstrssrmmrttrtst',
    'stttttsrusttttts',
    'rttrtttrutttrttr',
    'SSSSuuttutuuSSSS',
    'SvSSuutsutsuSSvS',
    'SvSvuttustsuvSvS',
    'SSSvuttustsuvSSS',
    'SSSvtttusttuvSSS',
    'SSSSuuuststuSSSS',
    'SSvSwwwwwxtuSvSS',
    'vSvvwwwwwwxuvvSv',
    '....wwwwwwww....',
    '....wwwwwwww....',
    '....wwwwwwww....',
    '....wwwwwwww....',
    '....wwwwwwww....',
    '....wxxwwxxw....',
    '....wwwwwwww....',
    '....wwwwwwww....',
    '....wwwwwwww....',
    '....wwwwwwww....',
    '....yyyyyyyy....',
    '....yyyyyyyy....',
    ] },
    alex: { w: 16, h: 32, palette: { A: '#e59947', B: '#e58d3f', C: '#dc933c', D: '#ebd3b3', E: '#f2daba', F: '#e4cba9', G: '#fbfbfb', H: '#236224', I: '#f2ddc2', J: '#eed6b6', K: '#efd9bb', L: '#f2dbbd', M: '#eed7b9', N: '#efbbb1', O: '#8cbe8a', P: '#8bba88', Q: '#7db27a', R: '#7aaf77', S: '#868761', T: '#e89d4c', U: '#7ab577', V: '#8a8b66', W: '#8c8d68', X: '#8f906b', Y: '#80825a', Z: '#77af75', a: '#e4c9a8', b: '#7db47a', c: '#e9d0af', d: '#e9d1b3', e: '#efd9bd', f: '#ecd4b8', g: '#4f804c', h: '#f2dfc8', i: '#183816', j: '#1a3f19', k: '#efdabf', l: '#684530', m: '#755038', n: '#79553d', o: '#805a40', p: '#6d4a33', q: '#724e36', r: '#6f4c35', s: '#865e46', t: '#78543c', u: '#5a5a5a', v: '#5d5d5d', w: '#616161', x: '#6b6b6b', y: '#636363', z: '#707070' }, rows: [
    '....ABABBABA....',
    '....BABACAAB....',
    '....ABACDDAB....',
    '....CCCDEFFA....',
    '....FGHEIHGF....',
    '....JKEIELME....',
    '....EIENNEED....',
    '....EEIEEIIE....',
    'OPQROSDEETTBBPPR',
    'PQOUOVDEEEATAPPR',
    'POPROQWDDBATPOQR',
    'SXSYZOOWWATQSXSY',
    'DDDaZOOQOTbPDDDa',
    'EEDDQOPOPOPPEEDD',
    'EEcDOOQOPOPOEEED',
    'dEEeOOZOQOOOdEED',
    'dIIfgOZOZOOgdIIf',
    'IIhfiiijjiijIIdf',
    'hhIkPOPOQPPOIhIk',
    'hIIfPlmmmmlPhIIf',
    '....lnopponl....',
    '....qnnllnnq....',
    '....rolqqlor....',
    '....llnqqnll....',
    '....rssrrssr....',
    '....lttllttl....',
    '....uvvuuvvu....',
    '....wxxwwxxw....',
    '....wxxwwxxw....',
    '....uyyuuyyu....',
    '....wxxwwxxw....',
    '....yzzyyzzy....',
    ] },
    sword: { w: 16, h: 16, palette: { A: '#444444', B: '#ffffff', C: '#181818', D: '#bebebe', E: '#d8d8d8', F: '#6b6b6b', G: '#969696', H: '#493615', I: '#684e1e', J: '#896727', K: '#281e0b' }, rows: [
    '.............AAA',
    '............ABBC',
    '...........ABDBC',
    '..........ABDBC.',
    '.........ABDEC..',
    '........ABDEC...',
    '..AA...AEDEC....',
    '..AFA.AEDEC.....',
    '...AGCEGEC......',
    '...AGGFEC.......',
    '....AFAC........',
    '...HICAAC.......',
    '..HJK.CCAC......',
    'AAIK....CC......',
    'AFC.............',
    'CCC.............',
    ] },
    bow: { w: 16, h: 16, palette: { A: '#493615', B: '#896727', C: '#684e1e', D: '#281e0b', E: '#6b6b6b', F: '#444444', G: '#969696' }, rows: [
    '................',
    '...........AAAA.',
    '........AAABCCBD',
    '......AABCBDDDD.',
    '.....AECDDD..F..',
    '....AEGE....F...',
    '...AEGE....F....',
    '...ACE....F.....',
    '..ABD....F......',
    '..ACD...F.......',
    '..ABD..F........',
    '.ABD..F.........',
    '.ACD.F..........',
    '.ACDF...........',
    '.ABD............',
    '..D.............',
    ] },
    potion: { w: 16, h: 16, palette: { A: '#d46d49', B: '#a94725', C: '#d4e5f7', D: '#ccafa5', E: '#b3cfec', F: '#973716', G: '#5d8fc2', H: '#8badd0' }, rows: [
    '................',
    '................',
    '.......AAB......',
    '......CDDDE.....',
    '......EBBFE.....',
    '.......E.G......',
    '.......E.G......',
    '......C...G.....',
    '.....C.E...G....',
    '....C.E.....G...',
    '....C.E.....G...',
    '....E.....H.G...',
    '....G.....H.G...',
    '.....G...H.G....',
    '......GGGGG.....',
    '................',
    ] },
    spyglass: { w: 16, h: 16, palette: { A: '#de923a', B: '#bd6a28', C: '#1e6566', D: '#339090', E: '#68bdbd', F: '#a05611', G: '#f4e063', H: '#ffffff', I: '#7e3f39', J: '#a85f58', K: '#532b0b', L: '#552925', M: '#331712' }, rows: [
    '................',
    '..........ABB...',
    '.........ACDEB..',
    '........FGDEHEB.',
    '.......FAGCDEEA.',
    '......FAGAGCDCA.',
    '......IGHGAGGA..',
    '.....IJGGABBK...',
    '....IJJIABBK....',
    '....LJILLMK.....',
    '...KFMLLM.......',
    '..KBBFMM........',
    '.KIBFK..........',
    '.MIIM...........',
    '..MM............',
    '................',
    ] },
    shield: { w: 16, h: 16, palette: { A: '#362b1b', B: '#967441', C: '#d8d8d8', D: '#b8945f', E: '#a8a8a8', F: '#745a36' }, rows: [
    '...AAAAAAAAAA...',
    '..ABBBBCCBBBBA..',
    '..ADDDDCCDDDDA..',
    '..ABBBBCCBBBBA..',
    '..ACCCCCCCCCDA..',
    '..ACCCCCCCCCBA..',
    '..ADDDDCEDDDDA..',
    '..ABBBBCEBBBBA..',
    '..ADDDDCEDDDDA..',
    '..AFFFFCEFFFFA..',
    '...ADDDDDDDDA...',
    '....AFFFFFFA....',
    '.....ADDDDA.....',
    '......AFFA......',
    '.......AA.......',
    '................',
    ] },
    emerald: { w: 16, h: 16, palette: { A: '#005300', B: '#dbffeb', C: '#41f384', D: '#17dd62', E: '#affdcd', F: '#00aa2c', G: '#002d00', H: '#009529', I: '#82f6ad', J: '#007b18' }, rows: [
    '................',
    '................',
    '......AAAA......',
    '.....ABCCDA.....',
    '....ABECCFDG....',
    '...ABEECCFFDG...',
    '...AEDDEEFHFG...',
    '...AEDDEIFJFG...',
    '...AEDDEIFJFG...',
    '...AEDDIIFJDG...',
    '...AEDDICJHDG...',
    '....AFHJJHIG....',
    '.....AFHJDG.....',
    '......GGGG......',
    '................',
    '................',
    ] },
    shovel: { w: 16, h: 16, palette: { A: '#372910', B: '#20180a', C: '#866526', D: '#6b511f', E: '#755821', F: '#493615', G: '#896727', H: '#281e0b', I: '#684e1e' }, rows: [
    '................',
    '................',
    '...........AAB..',
    '..........ACCDB.',
    '.........ACEDCB.',
    '........ACEDECB.',
    '.........FDECB..',
    '........FGHCB...',
    '.......FGH.B....',
    '......FIH.......',
    '.....FGH........',
    '....FIH.........',
    '..FFGH..........',
    '..FGH...........',
    '...HH...........',
    '................',
    ] },
    bread: { w: 16, h: 16, palette: { A: '#654b17', B: '#8c661e', C: '#a27924', D: '#bc8927', E: '#3f2e0e', F: '#4c3811', G: '#574114' }, rows: [
    '................',
    '.........AAAA...',
    '.......AABCCBA..',
    '......ABDDDDCBE.',
    '.....ADCBBDDDBE.',
    '....ADDDDCBDCBE.',
    '...ADDDDDDCDBAE.',
    '..ABCBBDDDDBBFE.',
    '..ADDDCBDDBBAE..',
    '.ABDDDDCDBBAE...',
    '.ACDDDDDBBAE....',
    '.ACCDDDBBAE.....',
    '.GBCCBBBAE......',
    '.GABBBBAE.......',
    '..FAAAFE........',
    '...FEEE.........',
    ] },
    torch: { w: 16, h: 16, palette: { A: '#ffd800', B: '#ff8f00', C: '#ffff97', D: '#ffffff', E: '#9f7f50', F: '#6d5736', G: '#957546', H: '#55452e', I: '#423522', J: '#3d301d', K: '#3b2e1b', L: '#372a17' }, rows: [
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '.......AB.......',
    '.......CD.......',
    '.......EF.......',
    '.......GH.......',
    '.......EI.......',
    '.......EH.......',
    '.......GH.......',
    '.......FJ.......',
    '.......EK.......',
    '.......FL.......',
    ] },
    heart: { w: 9, h: 9, palette: { A: '#ff1313', B: '#ffc8c8', C: '#bb1313' }, rows: [
    '.........',
    '..AA.AA..',
    '.ABAAAAA.',
    '.AAAAAAA.',
    '.CAAAAAC.',
    '..CAAAC..',
    '...CAC...',
    '....C....',
    '.........',
    ] },
    bone: { w: 16, h: 16, palette: { A: '#cbc6a5', B: '#e8e5d2', C: '#fcfbed', D: '#7b7e6b', E: '#fffffd' }, rows: [
    '................',
    '...........ABA..',
    '..........ABCDD.',
    '..........ACECBD',
    '..........ACCBAD',
    '.........ACCDDD.',
    '........ACCD....',
    '.......ACCD.....',
    '......ACCD......',
    '....AACCD.......',
    '..BBEECD........',
    '.BCEEED.........',
    '.ABAEBD.........',
    '..ADBAD.........',
    '....DD..........',
    '................',
    ] },
    redstone: { w: 16, h: 16, palette: { A: '#5c0700', B: '#720000', C: '#aa0f01', D: '#ff0000', E: '#410500', F: '#2d0000', G: '#340605' }, rows: [
    '................',
    '................',
    '................',
    '.......AA.......',
    '......ABCA......',
    '.....ACDCEF.....',
    '....ACDCBDEF....',
    '...ACCCDCEAEF...',
    '..ABDCBEDBECGF..',
    '..ACBCDCBEEAEF..',
    '..FECDCBECEEGF..',
    '...FECBEAEEGF...',
    '....FFGEEGFF....',
    '......FFFF......',
    '................',
    '................',
    ] },
    door: { w: 16, h: 16, palette: { A: '#695433', B: '#9f844d', C: '#6b6f7a', D: '#808b95', E: '#7e6237', F: '#967441' }, rows: [
    '................',
    '................',
    '...ABBBBBBBBB...',
    '...AB...B...B...',
    '...CB...B...B...',
    '...ABBBBBBBBB...',
    '...AB...B...B...',
    '...AB...B...B...',
    '...CBBBBBBDCB...',
    '...ABEEEBEEEB...',
    '...ABEFFBEFFB...',
    '...ABBBBBBBBB...',
    '...CBEEEBEEEB...',
    '...ABEFFBEFFB...',
    '...ABBBBBBBBB...',
    '...AAAAAAAAAA...',
    ] },
    book: { w: 16, h: 16, palette: { A: '#312104', B: '#522e10', C: '#654b17', D: '#543e13', E: '#44250a', F: '#5b5b5b', G: '#b7b7b7', H: '#999999', I: '#161005', J: '#d6d6d6' }, rows: [
    '................',
    '........AAA.....',
    '......AABCDA....',
    '....AABCCCCCA...',
    '..AABCCCECCCCA..',
    'AABDCCCCCECCCDA.',
    'ABDCCECCCCECCCEA',
    'AABCCCECCCCCEEF.',
    'AAGBCCCCCCEEHGH.',
    'IBJGBDCCEEHGGHAE',
    '.IBJGBEEHGGHAEII',
    '..IBJGHGGHAEII..',
    '...IBJGHEEII....',
    '....IBEEII......',
    '.....III........',
    '................',
    ] },
    bookFilled: { w: 16, h: 16, palette: { A: '#dedede', B: '#cacaca', C: '#adadad', D: '#391003', E: '#5d2210', F: '#6c2c19', G: '#75321e', H: '#4d1807', I: '#7f7f7f', J: '#6c6c6c', K: '#5b5b5b', L: '#b7b7b7', M: '#999999', N: '#161005', O: '#d6d6d6' }, rows: [
    '................',
    '....ABC.DDD.....',
    '...BAAADEFGH....',
    '...BAIAAGGFGH...',
    '..DCBBIBCDGFGH..',
    'DDEGCACAADDGFGH.',
    'HEGFGBAJAGDDGFDH',
    'HDEGFGBJBCGFDDK.',
    'HDLEGFAAJADDMLM.',
    'NEOLEGCAJAMLLMDH',
    '.NEOLEDBJBLMDDNN',
    '..NEOLMLBJDHNN..',
    '...NEOLMDJNN....',
    '....NEDHNN......',
    '.....NNN..N.....',
    '................',
    ] },
    compass: { w: 16, h: 16, palette: { A: '#353535', B: '#a8a8a8', C: '#828282', D: '#5e5e5e', E: '#181717', F: '#2f2f2f', G: '#ff1414', H: '#4f4d4d', I: '#646464', J: '#ffffff', K: '#d8d8d8' }, rows: [
    '................',
    '................',
    '.....AAAAAA.....',
    '...AABBCDCDAA...',
    '..EDCAFFFFADDE..',
    '.EDAFFFFGFFFADE.',
    '.EAFFFFFGFFFFAE.',
    '.EAFFFFHGIFFFAE.',
    '.EBAFFFFHFFFACE.',
    '.ECJJFFFFFFCCHE.',
    '.ECKKJJBKKCDHHE.',
    '..EBKKKCBBDDHE..',
    '...EEBKCBBDEE...',
    '.....EEEEEE.....',
    '................',
    '................',
    ] },
    map: { w: 16, h: 16, palette: { A: '#a7a848', B: '#eaeac7', C: '#daddaa', D: '#fcfcf2', E: '#878839', F: '#bbc177' }, rows: [
    '................',
    '................',
    '.........AA.....',
    '........ABCA....',
    '......AACDDBA...',
    '.....ABDDDDDCE..',
    '...AACDDDDDDDAE.',
    '..ACBDDDDDDDDCAE',
    '.ACBDDDDDDDDDBE.',
    '..ECBDDDDDDBCE..',
    '...ECBDDDDBEE...',
    '....ECBDBFE.....',
    '.....ECFEE......',
    '......EE........',
    '................',
    '................',
    ] }
};
